"""Build the thematic exercises from the reviewed public vocabulary manifest.

Dry-run by default. --apply downloads ARASAAC images, generates missing Marija
speech and cuts the owner's supplied narration. Source MP3s must already be in
ignored backups/body-parts-source/<video-id>.mp3. It never reads pupil data.
Requires ffmpeg, Pillow and edge-tts. No YouTube downloader runs in this script.
"""
import argparse
import asyncio
import base64
import hashlib
import io
import json
from pathlib import Path
import subprocess
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / 'backups/body-parts-source'
VOICE, RATE = 'mk-MK-MarijaNeural', '-10%'


async def build(themes):
    import edge_tts
    from PIL import Image
    images = CACHE / 'images'
    clips = CACHE / 'clips'
    marija = ROOT / 'backups/vezbi-audio/marija'
    for folder in (images, clips, marija):
        folder.mkdir(parents=True, exist_ok=True)
    # Refuse before producing partial bundles when a required recording is absent.
    videos = {w['audio']['video'] for g in themes for w in g['words'] if w['audio']['kind'] == 'author'}
    for video in videos:
        if not (CACHE / (video + '.mp3')).is_file():
            raise FileNotFoundError('Missing supplied narration: ' + video + '.mp3')
    decks, packs, files = [], [], []
    for group in themes:
        deck = dict(letter='', file=group['file'], kind='theme', title=group['title'],
                    words=[], sentences=[], img={}, audioSources={})
        pack = dict(format='mtb-vezbi-audio', version=1, sound=group['file'], locale='mk-MK', items={})
        for word in group['words']:
            text = word['text']
            key = group['file'] + ':' + text
            deck['words'].append(dict(w=text, img=key))
            if word.get('illustration'):
                picture = ROOT / 'vezbi' / word['illustration']
            else:
                pid = word['pictogram']
                assert isinstance(pid, int) and pid > 0
                picture = images / (str(pid) + '.png')
                if not picture.exists():
                    picture.write_bytes(urllib.request.urlopen(
                        f'https://static.arasaac.org/pictograms/{pid}/{pid}_300.png', timeout=30).read())
            # Image packing only: keep aspect ratio and alpha, no changes to artwork.
            with Image.open(picture) as im:
                im.thumbnail((300, 300))
                encoded = io.BytesIO()
                im.save(encoded, format='PNG', optimize=True)
            deck['img'][key] = 'data:image/png;base64,' + base64.b64encode(encoded.getvalue()).decode()
            source = word['audio']
            if source['kind'] == 'author':
                assert 0 <= source['start'] < source['end'] and source['end'] - source['start'] < 8
                digest = hashlib.sha256(json.dumps(source, sort_keys=True).encode()).hexdigest()[:24]
                clip = clips / (digest + '.mp3')
                if not clip.exists():
                    subprocess.run(['ffmpeg', '-v', 'error', '-y', '-ss', str(source['start']),
                                    '-i', str(CACHE / (source['video'] + '.mp3')),
                                    '-t', str(round(source['end'] - source['start'], 3)),
                                    '-map_metadata', '-1', '-ac', '1', '-ar', '24000',
                                    '-codec:a', 'libmp3lame', '-b:a', '64k', str(clip)], check=True)
            else:
                digest = hashlib.sha256((VOICE + RATE + text).encode()).hexdigest()[:24]
                clip = marija / (digest + '.mp3')
                if not clip.exists() or clip.stat().st_size < 100:
                    for attempt in range(3):
                        try:
                            temp = clip.with_suffix('.part')
                            await edge_tts.Communicate(text, VOICE, rate=RATE).save(str(temp))
                            if temp.stat().st_size < 100:
                                raise ValueError('Empty speech response')
                            temp.replace(clip)
                            break
                        except Exception:
                            if attempt == 2:
                                raise
                            await asyncio.sleep(2 * (attempt + 1))
            pack['items'][text] = 'data:audio/mpeg;base64,' + base64.b64encode(clip.read_bytes()).decode()
            deck['audioSources'][text] = source
            files.append((clip, group['file'] + '/' + text + '.mp3'))
        decks.append(deck)
        packs.append(pack)
        print(group['title'] + ': ' + str(len(group['words'])) + ' pictures and clips ready', flush=True)
    # Publish only once every theme is complete.
    (ROOT / 'vezbi/temi.js').write_text(
        '// Generated by scripts/vezbi-themes.py from themes-manifest.json.\n'
        '// ARASAAC: Sergio Palao / Government of Aragon, CC BY-NC-SA; cezve: generated supplement.\n'
        'window.VEZBI_THEMES = ' + json.dumps(decks, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf8')
    for pack in packs:
        name = pack['sound']
        (ROOT / 'vezbi/audio' / (name + '.js')).write_text(
            '// Owner narration / Marija fallback; sources in themes-manifest.json.\n'
            'window.VEZBI_AUDIO = window.VEZBI_AUDIO || {};\n'
            'window.VEZBI_AUDIO[' + json.dumps(name) + '] = ' +
            json.dumps(pack, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf8')
    with zipfile.ZipFile(CACHE / 'Temi-audio.zip', 'w', zipfile.ZIP_DEFLATED) as z:
        for path, name in files:
            z.write(path, 'mp3/' + name)
        for pack in packs:
            z.writestr('packs/' + pack['sound'] + '.json', json.dumps(pack, ensure_ascii=False))
        z.writestr('PROCITAJ.txt', 'MP3: по една снимка за секој поим.\n'
                   'JSON: избери ја соодветната тема во Вежби, па ⋯ → Внеси аудиопакет.\n'
                   'Авторски видеоснимки со Марија за недостапните/изменетите поими.\n')
    print('Complete: 11 themes, offline images, audio bundles and backups/body-parts-source/Temi-audio.zip', flush=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    themes = json.loads((ROOT / 'vezbi/themes-manifest.json').read_text(encoding='utf8'))['themes']
    print(f'{len(themes)} themes; {sum(len(g["words"]) for g in themes)} terms.')
    if args.apply:
        asyncio.run(build(themes))
    else:
        print('Dry run. Add --apply to generate the complete offline catalogue.')
