"""Build the reviewed Word vocabulary as offline ARASAAC cards and Marija audio.

Dry run by default; --apply downloads only official pictograms and creates
speech for public vocabulary. The original Word file is never published.
Both exercises and WBACC consume the same generated bukvi.js catalogue.
"""
import argparse
import asyncio
import base64
import hashlib
import io
import json
from pathlib import Path
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / 'backups/stamp-source'
VOICE, RATE = 'mk-MK-MarijaNeural', '-10%'


async def build(manifest):
    import edge_tts
    from PIL import Image
    images = CACHE / 'images'
    clips = ROOT / 'backups/vezbi-audio/marija'
    images.mkdir(parents=True, exist_ok=True)
    clips.mkdir(parents=True, exist_ok=True)
    items, audio = [], {}
    for word in manifest['items']:
        pid, text = word['pictogram'], word['text']
        picture = images / (str(pid) + '.png')
        if not picture.exists():
            picture.write_bytes(urllib.request.urlopen(
                f'https://static.arasaac.org/pictograms/{pid}/{pid}_300.png', timeout=30).read())
        with Image.open(picture) as im:
            im.thumbnail((300, 300))
            encoded = io.BytesIO()
            im.save(encoded, format='PNG', optimize=True)
        item = dict(word, image='data:image/png;base64,' + base64.b64encode(encoded.getvalue()).decode())
        items.append(item)
        digest = hashlib.sha256((VOICE + RATE + text).encode()).hexdigest()[:24]
        clip = clips / (digest + '.mp3')
        if not clip.exists() or clip.stat().st_size < 100:
            for attempt in range(5):
                try:
                    temp = clip.with_suffix('.part')
                    await edge_tts.Communicate(text, VOICE, rate=RATE).save(str(temp))
                    if temp.stat().st_size < 100:
                        raise ValueError('Empty speech response')
                    temp.replace(clip)
                    await asyncio.sleep(1)
                    break
                except Exception:
                    if attempt == 4:
                        raise
                    await asyncio.sleep(10 * (attempt + 1))
        audio[text] = 'data:audio/mpeg;base64,' + base64.b64encode(clip.read_bytes()).decode()
        print(text + ' ready', flush=True)
    # Publish complete assets only, with no runtime network requirement.
    catalogue = dict(version=1, credit=manifest['credit'], categories=manifest['categories'], items=items)
    dump = lambda value: json.dumps(value, ensure_ascii=False, separators=(',', ':'))
    (ROOT / 'vezbi/bukvi.js').write_text(
        '// Generated by scripts/vezbi-letters.py; sources in letters-manifest.json.\n'
        '// ARASAAC: Sergio Palao / Government of Aragon, CC BY-NC-SA.\n'
        'window.LETTER_CATALOG = ' + dump(catalogue) + ';\n', encoding='utf8')
    (ROOT / 'vezbi/audio/letters.js').write_text(
        '// Marija, mk-MK, generated from the public Word vocabulary.\n'
        'window.VEZBI_AUDIO = window.VEZBI_AUDIO || {};\n'
        'window.VEZBI_AUDIO.letters = {items:' + dump(audio) + '};\n', encoding='utf8')
    print(f'Complete: {len(items)} cards and recordings, {len(manifest["categories"])} categories.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--apply', action='store_true')
    args = parser.parse_args()
    manifest = json.loads((ROOT / 'vezbi/letters-manifest.json').read_text(encoding='utf8'))
    print(f'{len(manifest["items"])} terms; {len(manifest["pending"])} awaiting exact pictograms.')
    if args.apply:
        asyncio.run(build(manifest))
