/**
 * The index at the top of the long reference files.
 *
 *     npm run docs:toc      rewrite the index of every file below
 *     npm run check:toc     exit 1 if any index is stale (the pre-commit hook)
 *
 * WHY. An agent deciding whether a file is relevant often reads only its first
 * hundred lines. CLAUDE.md is close to a thousand and its traps start at line
 * 316; a rule past the preview may as well not exist. So each long file says
 * what it holds before anything else.
 *
 * WHY A SCRIPT. An index kept by hand is right on the day it is written. This
 * one is derived from the headings, and the commit is refused when it has
 * drifted — the same reasoning as check:names: a rule nothing enforces is a
 * wish.
 *
 * The index lives between two marker lines. It lists section NAMES, never line
 * numbers: a name can be searched for and does not move when a line is added.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../..');
const OPEN = '<!-- index: generated by `npm run docs:toc` in server/ — do not edit by hand -->';
const CLOSE = '<!-- /index -->';

type Entry = {
    file: string;
    /** `##` sections are always listed; this adds the bold lead of each top-level bullet under one of them. */
    bulletsUnder?: string;
    /** `###` entries listed under this section, newest first as written, at most `limit`. */
    newestUnder?: string;
    limit?: number;
};

const FILES: Entry[] = [
    { file: 'CLAUDE.md', bulletsUnder: 'Traps already hit' },
    { file: 'AGENTS.md', bulletsUnder: 'Traps already hit' },
    { file: 'SOSTOJBA.md', newestUnder: 'Каде сме сега', limit: 12 },
    { file: 'docs/APP-CONTRACT.md' },
    { file: 'docs/HISTORY.md' },
    { file: 'docs/WORKSPACE-RELEASE.md' },
    { file: 'docs/SYNC.md' }
];

function indexOf(lines: string[], entry: Entry): string[] {
    const out: string[] = [];
    let section = '';
    let listed = 0;
    let fenced = false;
    for (const line of lines) {
        if (/^```/.test(line)) { fenced = !fenced; continue; }
        if (fenced) continue;
        const h2 = /^## (.+?)\s*$/.exec(line);
        if (h2) { section = h2[1]; listed = 0; out.push(`- ${section}`); continue; }
        if (entry.bulletsUnder && section.startsWith(entry.bulletsUnder)) {
            // The bold lead of a trap; a lead that wraps is cut at the line end.
            const lead = /^- \*\*(.+?)(?:\*\*|$)/.exec(line);
            if (lead) out.push(`  - ${lead[1].replace(/[.:,]$/, '')}`);
        }
        if (entry.newestUnder && section.startsWith(entry.newestUnder)) {
            const h3 = /^### (.+?)\s*$/.exec(line);
            if (h3 && listed < (entry.limit ?? 10)) { out.push(`  - ${h3[1]}`); listed++; }
        }
    }
    return out;
}

function withIndex(text: string, entry: Entry): string {
    const eol = text.includes('\r\n') ? '\r\n' : '\n';
    const lines = text.split(/\r?\n/);
    const from = lines.indexOf(OPEN), to = lines.indexOf(CLOSE);
    if (from < 0 || to < from) throw new Error(`${entry.file}: the index markers are missing — add the two marker lines near the top first`);
    const body = [...lines.slice(0, from), ...lines.slice(to + 1)];
    const block = [OPEN, '', `**In this file** (${body.length} lines; search for a name to jump to it):`, '', ...indexOf(body, entry), '', CLOSE];
    return [...lines.slice(0, from), ...block, ...lines.slice(to + 1)].join(eol);
}

const check = process.argv.includes('--check');
const stale: string[] = [];
for (const entry of FILES) {
    const path = resolve(ROOT, entry.file);
    const now = readFileSync(path, 'utf8');
    const next = withIndex(now, entry);
    if (next === now) continue;
    if (check) stale.push(entry.file);
    else { writeFileSync(path, next, 'utf8'); console.log(`index rewritten: ${entry.file}`); }
}
if (check && stale.length) {
    console.error(`The index at the top of ${stale.join(', ')} no longer matches the headings.`);
    console.error('Run `npm run docs:toc` in server/ and commit the result.');
    process.exit(1);
}
if (check) console.log(`Index checked in ${FILES.length} files — all current.`);
